# Generated by Django 5.2.7 on 2025-10-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('predictor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictors', to='dataset.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_predictors', to='authapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PredictorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='predictors.predictor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictor_permissions', to='authapp.user')),
            ],
            options={
                'unique_together': {('predictor', 'user')},
            },
        ),
    ]
