# Generated by Django 5.2.7 on 2025-10-09 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_predictors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predictorpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictor_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
