# Generated by Django 5.2.7 on 2025-10-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0002_alter_predictor_owner_alter_predictorpermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
