# Generated by Django 5.2.7 on 2025-10-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0003_predictor_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedPredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='predictors.predictor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_predictors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'predictor')},
            },
        ),
    ]
