# Generated by Django 5.2.7 on 2025-10-19 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0005_alter_pinnedpredictor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinnedpredictor',
            options={'ordering': ['-pinned_at'], 'verbose_name': 'Pinned Predictor', 'verbose_name_plural': 'Pinned Predictors'},
        ),
        migrations.AddField(
            model_name='predictor',
            name='allow_admin_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictor',
            name='c_param_search_scope',
            field=models.CharField(default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='cox_feature_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictor',
            name='marginal_loss_type',
            field=models.CharField(default='weighted', max_length=50),
        ),
        migrations.AddField(
            model_name='predictor',
            name='mrmr_feature_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictor',
            name='mtlr_predictor',
            field=models.CharField(default='stable', max_length=50),
        ),
        migrations.AddField(
            model_name='predictor',
            name='num_time_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='objective_function',
            field=models.CharField(default='log-likelihood', max_length=50),
        ),
        migrations.AddField(
            model_name='predictor',
            name='regularization',
            field=models.CharField(choices=[('l1', 'L1'), ('l2', 'L2')], default='l2', max_length=5),
        ),
        migrations.AddField(
            model_name='predictor',
            name='run_cross_validation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='standardize_features',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='time_unit',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='predictor',
            name='tune_parameters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='use_predefined_folds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictor',
            name='use_smoothed_log_likelihood',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
