# Generated by Django 5.2.7 on 2025-10-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0006_alter_pinnedpredictor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pinnedpredictor',
            table='predictors_pinnedpredictor',
        ),
    ]
