# Generated by Django 5.2.7 on 2025-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_alter_pinnedpredictor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictorpermission',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='time_unit',
            field=models.CharField(choices=[('day', 'Day'), ('hour', 'Hour'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10),
        ),
    ]
