# Generated by Django 5.2.7 on 2025-11-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('predictors', '0008_predictorpermission_role_alter_predictor_time_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictors', to='folders.folder'),
        ),
    ]
