# Generated by Django 5.2.8 on 2025-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0009_predictor_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='ml_model_id',
            field=models.CharField(blank=True, help_text='ID of the trained ML model from the ML API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='ml_model_metrics',
            field=models.JSONField(blank=True, help_text='Performance metrics from ML model training (C-index, IBS, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='ml_selected_features',
            field=models.JSONField(blank=True, help_text='List of features used in ML model training', null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='ml_trained_at',
            field=models.DateTimeField(blank=True, help_text='When the ML model was trained', null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='ml_training_status',
            field=models.CharField(choices=[('not_trained', 'Not Trained'), ('training', 'Training'), ('trained', 'Trained'), ('failed', 'Failed')], default='not_trained', max_length=20),
        ),
    ]
