# Generated by Django 5.2.8 on 2025-11-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0010_predictor_ml_model_id_predictor_ml_model_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
