# Generated by Django 5.2.8 on 2025-11-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0011_alter_predictor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='ml_model_id',
        ),
        migrations.AddField(
            model_name='predictor',
            name='model_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the trained model from the ML server.', null=True, unique=True),
        ),
    ]
