# Generated by Django 5.2.8 on 2025-11-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0012_remove_predictor_ml_model_id_predictor_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='ml_training_error',
            field=models.TextField(blank=True, help_text='Error message if training failed', null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='ml_training_progress',
            field=models.JSONField(blank=True, help_text='Training progress information (current_epoch, total_epochs, time_per_epoch, etc.)', null=True),
        ),
    ]
