# Generated by Django 5.2.8 on 2025-11-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0012_remove_predictor_ml_model_id_predictor_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='c_param_search_scope',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='cox_feature_selection',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='marginal_loss_type',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='mrmr_feature_selection',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='mtlr_predictor',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='num_time_points',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='objective_function',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='regularization',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='run_cross_validation',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='standardize_features',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='time_unit',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='tune_parameters',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='use_predefined_folds',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='use_smoothed_log_likelihood',
        ),
        migrations.AddField(
            model_name='predictor',
            name='activation',
            field=models.CharField(choices=[('ReLU', 'ReLU'), ('LeakyReLU', 'LeakyReLU'), ('PReLU', 'PReLU'), ('Tanh', 'Tanh'), ('Sigmoid', 'Sigmoid'), ('ELU', 'ELU'), ('SELU', 'SELU')], default='ReLU', help_text='Activation function', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='batch_size',
            field=models.PositiveIntegerField(default=128, help_text='Batch size for training'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='decensor_method',
            field=models.CharField(choices=[('uncensored', 'Uncensored'), ('margin', 'Margin'), ('PO', 'PO'), ('sampling', 'Sampling')], default='uncensored', help_text='Method for handling censored data', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='dropout',
            field=models.FloatField(default=0.4, help_text='Dropout rate (0-1)'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='early_stop',
            field=models.BooleanField(default=True, help_text='Enable early stopping'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='error_f',
            field=models.CharField(default='Quantile', help_text='Error function for conformal prediction', max_length=50),
        ),
        migrations.AddField(
            model_name='predictor',
            name='interpolate',
            field=models.CharField(choices=[('Linear', 'Linear'), ('Pchip', 'Pchip')], default='Pchip', help_text='Interpolation method for predictions', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='lam',
            field=models.FloatField(blank=True, help_text='Lambda parameter for LogNormalNN d-calibration', null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='lr',
            field=models.FloatField(default=0.001, help_text='Learning rate'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='model',
            field=models.CharField(choices=[('MTLR', 'MTLR'), ('DeepHit', 'DeepHit'), ('CoxPH', 'CoxPH'), ('AFT', 'AFT'), ('GB', 'GB'), ('CoxTime', 'CoxTime'), ('CQRNN', 'CQRNN'), ('LogNormalNN', 'LogNormalNN'), ('KM', 'KM')], default='MTLR', help_text='Survival analysis model type', max_length=50),
        ),
        migrations.AddField(
            model_name='predictor',
            name='mono_method',
            field=models.CharField(choices=[('ceil', 'Ceil'), ('floor', 'Floor'), ('bootstrap', 'Bootstrap')], default='ceil', help_text='Method for ensuring monotonicity', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='n_epochs',
            field=models.PositiveIntegerField(default=10000, help_text='Maximum training iterations'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='n_exp',
            field=models.PositiveIntegerField(default=1, help_text='Number of experimental runs'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='n_quantiles',
            field=models.PositiveIntegerField(default=49, help_text='Number of quantiles'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='n_sample',
            field=models.PositiveIntegerField(blank=True, help_text='Number of samples when using sampling decensor method', null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='neurons',
            field=models.JSONField(default=list, help_text='Hidden layer sizes as array, e.g. [64, 64]'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='norm',
            field=models.BooleanField(default=True, help_text='Use batch normalization'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='post_process',
            field=models.CharField(choices=[('CSD', 'CSD'), ('CSD-iPOT', 'CSD-iPOT')], default='CSD', help_text='Post-processing method for predictions', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='seed',
            field=models.IntegerField(default=0, help_text='Random seed for reproducibility'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='time_bins',
            field=models.PositiveIntegerField(blank=True, help_text='Number of time bins (for MTLR, CoxPH, CQRNN, LogNormalNN)', null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='use_train',
            field=models.BooleanField(default=True, help_text='Include training data in conformal prediction'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='weight_decay',
            field=models.FloatField(default=0.0, help_text='L2 regularization strength'),
        ),
    ]
