# Generated by Django 5.2.8 on 2025-12-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0013_predictor_ml_training_error_and_more'),
        ('predictors', '0013_remove_predictor_c_param_search_scope_and_more'),
    ]

    operations = [
    ]
