# Generated by Django 5.2.7 on 2025-10-26 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the folder', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the folder')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the folder is private (True) or public (False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FolderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_folder_items', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_items', to='folders.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View')], default='view', help_text='Type of permission granted', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='folders.folder')),
                ('granted_by', models.ForeignKey(help_text='User who granted this permission', on_delete=django.db.models.deletion.CASCADE, related_name='granted_folder_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'is_private'], name='folders_fol_owner_i_6dd2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_private'], name='folders_fol_is_priv_d7470a_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_at'], name='folders_fol_created_f8980e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['folder', 'content_type'], name='folders_fol_folder__857381_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['content_type', 'object_id'], name='folders_fol_content_396a41_idx'),
        ),
        migrations.AddIndex(
            model_name='folderitem',
            index=models.Index(fields=['added_at'], name='folders_fol_added_a_c376d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderitem',
            unique_together={('folder', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['user'], name='folders_fol_user_id_4cdca9_idx'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['folder'], name='folders_fol_folder__612a56_idx'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['granted_at'], name='folders_fol_granted_c391bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderpermission',
            unique_together={('folder', 'user', 'permission_type')},
        ),
    ]
