# Generated by Django 5.2.8 on 2025-11-30 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='folders.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Folder',
                'verbose_name_plural': 'Pinned Folders',
                'db_table': 'folders_pinnedfolder',
                'indexes': [models.Index(fields=['user'], name='folders_pin_user_id_b24ecb_idx'), models.Index(fields=['folder'], name='folders_pin_folder__423ab8_idx')],
                'unique_together': {('user', 'folder')},
            },
        ),
    ]
