# Generated by Django 5.2.7 on 2025-10-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
